titan.dbname=./db/ycsb-titan

# 1GB block cache
titan.cache_size=1073741824

titan.format=single
titan.destroy=false
titan.create_if_missing=true
titan.disable_auto_compactions=false
titan.disableWAL=true
titan.blob_size=512
titan.min_blob_size=512
titan.blob_file_size=67108864
titan.enable_blob_garbage_collection=false
titan.blob_garbage_collection_age_cutoff=0.25

# Load options from file
# titan.optionsfile=titan/options.ini

# Below options are ignored if options file is used
titan.compression=snappy
titan.max_background_jobs=2
titan.target_file_size_base=67108864
titan.target_file_size_multiplier=1
titan.max_bytes_for_level_base=268435456
titan.write_buffer_size=67108864
titan.max_open_files=-1
titan.max_write_buffer_number=2
titan.use_direct_io_for_flush_compaction=false
titan.use_direct_reads=true
titan.allow_mmap_writes=false
titan.allow_mmap_reads=false
titan.bloom_bits=10

# deprecated since rocksdb 8.0
titan.compressed_cache_size=0

titan.increase_parallelism=false
titan.optimize_level_style_compaction=false
